channels:
  - conda-forge

dependencies:
  - aiohttp
  - jupyter_contrib_nbextensions
  - jupyter-server-proxy
  - jupyterhub-singleuser
  - python=3.10
  - nbgitpuller
  - pip
  - git
  - numpy
  - scipy>=1.1
  - cython
  - lxml
  - astropy
  - pandas
  - scikit-image
  - h5py
  - openblas
# - pip:
#   - some-package-that-can-only-be-installed-with-pip
#